// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4kHRJMnHxhtBkcU4crmGNFLHwkX2RGS8',
    appId: '1:67056708090:web:5949aa84d4e8418e6ddc43',
    messagingSenderId: '67056708090',
    projectId: 'cloudyml-app',
    authDomain: 'cloudyml-app.firebaseapp.com',
    databaseURL: 'https://cloudyml-app-default-rtdb.firebaseio.com',
    storageBucket: 'cloudyml-app.appspot.com',
    measurementId: 'G-X886HKN9R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjeM1nHxStEbUaUoryKEmu3wKE9-96p8c',
    appId: '1:67056708090:android:450545f5e7d0a4f06ddc43',
    messagingSenderId: '67056708090',
    projectId: 'cloudyml-app',
    databaseURL: 'https://cloudyml-app-default-rtdb.firebaseio.com',
    storageBucket: 'cloudyml-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5nVKxIMnW4eq4C9rRRO4cpAkY19PJ96s',
    appId: '1:67056708090:ios:b978a06bff8df2366ddc43',
    messagingSenderId: '67056708090',
    projectId: 'cloudyml-app',
    databaseURL: 'https://cloudyml-app-default-rtdb.firebaseio.com',
    storageBucket: 'cloudyml-app.appspot.com',
    androidClientId: '67056708090-204m5o5sqnqlgqc87j45h6icfbke6e3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobPortalCloudyml',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5nVKxIMnW4eq4C9rRRO4cpAkY19PJ96s',
    appId: '1:67056708090:ios:ce77d88f6e6acacd6ddc43',
    messagingSenderId: '67056708090',
    projectId: 'cloudyml-app',
    databaseURL: 'https://cloudyml-app-default-rtdb.firebaseio.com',
    storageBucket: 'cloudyml-app.appspot.com',
    androidClientId: '67056708090-204m5o5sqnqlgqc87j45h6icfbke6e3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobPortalCloudyml.RunnerTests',
  );
}
